version: '3.8'

services:
  carbon-explorer:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NEXT_PUBLIC_REGISTRY_API_URL=http://localhost:3000
      - NEXT_PUBLIC_ADAPTER_API_URL=http://localhost:3001
      - NEXT_PUBLIC_RPC_URL=http://localhost:8545
      - NEXT_PUBLIC_CHAIN_ID=31337
      - NEXT_PUBLIC_BLOCK_EXPLORER_URL=http://localhost:3001
      - NEXT_PUBLIC_FEATURE_HOLDERS=false
      - NEXT_PUBLIC_FEATURE_SUBGRAPH=false
      - NEXT_PUBLIC_BRAND_NAME=Sim Registry
    depends_on:
      - registry-api
      - adapter-api
    networks:
      - carbon-network

  registry-api:
    image: registry-api:latest
    ports:
      - "3000:3000"
    networks:
      - carbon-network

  adapter-api:
    image: adapter-api:latest
    ports:
      - "3001:3001"
    networks:
      - carbon-network

networks:
  carbon-network:
    driver: bridge
